"use client";
import Link from "next/link";
import { Facebook, Instagram, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import BrandLogo from "@/components/layout/BrandLogo";
import { useLanguage } from "@/components/layout/LanguageProvider";
import { translate } from "@/lib/i18n";
import { siteConfig } from "@/lib/site";

export default function Footer() {
  const { language } = useLanguage();
  const t = translate({ en: { desc: "KNLTC — Japan Education & Career Consultancy.", quick: "Quick Links", rights: "All rights reserved.", links: ["Study in Japan", "Work in Japan", "Japanese Language", "Store", "Blog", "Contact"] }, bn: { desc: "KNLTC — Japan Education & Career Consultancy।", quick: "দ্রুত লিংক", rights: "সর্বস্বত্ব সংরক্ষিত।", links: ["জাপানে পড়াশোনা", "জাপানে কাজ", "জাপানি ভাষা", "স্টোর", "ব্লগ", "যোগাযোগ"] }, ja: { desc: "KNLTC — 日本留学・キャリアコンサルティング。", quick: "クイックリンク", rights: "無断転載を禁じます。", links: ["日本留学", "日本就職", "日本語", "ストア", "ブログ", "お問い合わせ"] } }, language);
  return <footer className="bg-red-800 py-12 text-white/90"><div className="container-narrow"><div className="mb-8 grid gap-8 sm:grid-cols-2 lg:grid-cols-3"><div><div className="mb-4 w-fit rounded-xl bg-white/10 p-3"><BrandLogo compact inverse /></div><p className="text-sm leading-relaxed">{t.desc}</p></div><div><h4 className="mb-3 font-bold text-white">{t.quick}</h4><ul className="space-y-2 text-sm"><li><Link href="/study-in-japan">{t.links[0]}</Link></li><li><Link href="/work-in-japan">{t.links[1]}</Link></li><li><Link href="/japanese-language">{t.links[2]}</Link></li><li><Link href="/store">{t.links[3]}</Link></li><li><Link href="/blog">{t.links[4]}</Link></li><li><Link href="/contact">{t.links[5]}</Link></li></ul></div><div><h4 className="mb-3 font-bold text-white">যোগাযোগ</h4><ul className="space-y-2 text-sm"><li className="flex items-center gap-2"><Phone className="h-3.5 w-3.5" /> <a href={siteConfig.phoneHref}>{siteConfig.phoneDisplay}</a></li><li className="flex items-center gap-2"><Mail className="h-3.5 w-3.5" /> <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a></li><li className="flex items-start gap-2"><MapPin className="mt-0.5 h-3.5 w-3.5" /> <span>{siteConfig.location}</span></li></ul></div></div><div className="mb-6 flex gap-5"><a href="https://web.facebook.com/KurobeNihongoLanguageTrainingCenter" target="_blank" rel="noopener noreferrer"><Facebook className="h-4 w-4" /></a><a href="https://www.instagram.com/knltc.official" target="_blank" rel="noopener noreferrer"><Instagram className="h-4 w-4" /></a><a href={siteConfig.whatsappHref} target="_blank" rel="noopener noreferrer"><MessageCircle className="h-4 w-4" /></a></div><div className="border-t border-white/15 pt-6 text-center text-sm">© {new Date().getFullYear()} KNLTC. {t.rights}</div></div></footer>;
}
