"use client";

import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { useLanguage } from "@/components/layout/LanguageProvider";
import { translate } from "@/lib/i18n";

export default function StudyInJapanPage() {
  const { language } = useLanguage();
  const t = translate({ bn: { title: "জাপানে পড়াশোনার সম্পূর্ণ গাইডলাইন", subtitle: "ভাষা স্কুল, বিশ্ববিদ্যালয় ভর্তি, স্টুডেন্ট ভিসা, ডকুমেন্টেশন, ইন্টারভিউ প্রস্তুতি ও জাপানে পৌঁছানোর পর গাইডলাইন—সবকিছু এক জায়গায়।", why: "কেন জাপানে পড়াশোনা?", pathways: "স্টাডি পাথওয়ে", visa: "স্টুডেন্ট ভিসা সাপোর্ট", relationTitle: "জাপানের শিক্ষা প্রতিষ্ঠানের সাথে কাজের লক্ষ্য", relationText: "KNLTC জাপানের শিক্ষা প্রতিষ্ঠানগুলোর সাথে কাজের সুযোগ তৈরি করছে এবং শিক্ষার্থীদের জন্য নির্ভরযোগ্য admission guidance দেওয়ার লক্ষ্য নিয়ে কাজ করছে।", timeline: "প্রসেস টাইমলাইন", faq: "প্রশ্নোত্তর", finalTitle: "জাপানে পড়াশোনার পরিকল্পনা করছেন?", consult: "ফ্রি কনসাল্টেশন নিন", whatsapp: "হোয়াটসঅ্যাপে কথা বলুন" }, en: { title: "Complete Guideline for Studying in Japan", subtitle: "Language school, university admission, student visa, documentation, interview preparation, and post-arrival guidance in one place.", why: "Why Study in Japan?", pathways: "Study Pathways", visa: "Student Visa Support", relationTitle: "Goal of Working with Japanese Educational Institutions", relationText: "KNLTC is creating opportunities to work with Japanese educational institutions and aims to provide reliable admission guidance for students.", timeline: "Process Timeline", faq: "FAQ", finalTitle: "Planning to study in Japan?", consult: "Get Free Consultation", whatsapp: "Talk on WhatsApp" }, ja: { title: "日本留学の完全ガイドライン", subtitle: "日本語学校、大学進学、学生ビザ、書類準備、面接対策、渡航後ガイダンスまで一括サポート。", why: "なぜ日本で学ぶのか？", pathways: "留学パスウェイ", visa: "学生ビザサポート", relationTitle: "日本の教育機関との連携に向けた目標", relationText: "KNLTCは日本の教育機関との連携機会を広げ、学生に信頼できる入学ガイダンスを提供することを目指しています。", timeline: "プロセスタイムライン", faq: "よくある質問", finalTitle: "日本留学を計画していますか？", consult: "無料相談を受ける", whatsapp: "WhatsAppで相談" } }, language);

  const why = translate({ bn: ["উন্নত শিক্ষা ব্যবস্থা", "নিরাপদ ও শৃঙ্খলাপূর্ণ পরিবেশ", "পড়াশোনার পাশাপাশি ভবিষ্যৎ ক্যারিয়ার সুযোগ", "জাপানি ভাষা শেখার মাধ্যমে দীর্ঘমেয়াদি সম্ভাবনা"], en: ["Advanced education system", "Safe and disciplined environment", "Future career opportunities alongside study", "Long-term potential through Japanese language"], ja: ["先進的な教育制度", "安全で規律ある環境", "学業と将来のキャリア機会", "日本語習得による長期的な可能性"] }, language);
  const pathways = translate({ bn: ["ভাষা স্কুল", "বিশ্ববিদ্যালয় ভর্তি", "ভোকেশনাল / সেনমন স্কুল", "উচ্চশিক্ষার পথ"], en: ["Language school", "University admission", "Vocational / Senmon school", "Higher study pathway"], ja: ["日本語学校", "大学進学", "職業・専門学校", "高等教育への進路"] }, language);
  const checklist = translate({ bn: ["যোগ্যতা যাচাই", "স্কুল/প্রোগ্রাম নির্বাচন", "আবেদন ফাইল প্রস্তুতি", "ফাইন্যান্সিয়াল ডকুমেন্ট গাইডলাইন", "ইন্টারভিউ প্রস্তুতি", "ভিসা প্রসেস গাইডলাইন", "প্রি-ডিপার্চার সাপোর্ট"], en: ["Eligibility review", "School/program selection", "Application file preparation", "Financial document guideline", "Interview preparation", "Visa process guideline", "Pre-departure support"], ja: ["適性確認", "学校・プログラム選定", "申請書類の準備", "資金書類ガイドライン", "面接準備", "ビザ手続きガイド", "渡航前サポート"] }, language);
  const timeline = translate({ bn: ["ফ্রি কনসাল্টেশন", "যোগ্যতা যাচাই", "স্কুল/প্রোগ্রাম নির্বাচন", "আবেদন ও ডকুমেন্টেশন", "ইন্টারভিউ প্রস্তুতি", "ভিসা প্রসেস", "প্রি-ডিপার্চার গাইডলাইন", "জাপানে পৌঁছানোর পর সাপোর্ট"], en: ["Free consultation", "Eligibility review", "School/program selection", "Application and documentation", "Interview preparation", "Visa process", "Pre-departure guideline", "After-arrival support in Japan"], ja: ["無料相談", "適性確認", "学校・プログラム選定", "申請と書類準備", "面接準備", "ビザ手続き", "渡航前ガイド", "渡航後サポート"] }, language);
  const faqs = translate({ bn: ["জাপানে পড়তে যেতে কি জাপানি ভাষা লাগে?", "IELTS লাগে কি?", "কত সময় লাগে?", "কত খরচ হতে পারে?", "পড়াশোনার পরে কাজের সুযোগ আছে কি?"], en: ["Do I need Japanese language skills to study in Japan?", "Is IELTS required?", "How long does the process take?", "How much can it cost?", "Are there work opportunities after study?"], ja: ["日本留学に日本語は必要ですか？", "IELTSは必要ですか？", "どれくらい時間がかかりますか？", "費用はどのくらいですか？", "卒業後に就職機会はありますか？"] }, language);

  return <main className="section-padding bg-gradient-to-b from-white via-red-50/20 to-green-50/30"><div className="container-narrow space-y-6">
    <section className="fade-up rounded-3xl border bg-white p-8 shadow-sm md:p-10"><h1 className="text-3xl font-extrabold text-red-700 md:text-4xl">{t.title}</h1><p className="mt-3 text-muted-foreground">{t.subtitle}</p></section>
    <section><h2 className="section-title fade-up">{t.why}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{why.map((item, i) => <div key={item} className="fade-up card-lift rounded-xl border bg-white p-4" style={{ animationDelay: `${i * 80}ms` }}>{item}</div>)}</div></section>
    <section><h2 className="section-title fade-up">{t.pathways}</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{pathways.map((item, i) => <div key={item} className="fade-up card-lift rounded-xl border border-green-100 bg-green-50/50 p-4 font-medium" style={{ animationDelay: `${i * 80}ms` }}>{item}</div>)}</div></section>
    <section className="fade-up rounded-2xl border bg-white p-6"><h2 className="section-title text-2xl">{t.visa}</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{checklist.map((item) => <div key={item} className="card-lift flex items-start gap-2 rounded-lg bg-red-50 p-3"><CheckCircle2 className="mt-0.5 h-4 w-4 text-green-700" />{item}</div>)}</div></section>
    <section className="fade-up rounded-2xl border bg-white p-6"><h2 className="section-title text-2xl">{t.relationTitle}</h2><p className="mt-3 leading-relaxed text-muted-foreground">{t.relationText}</p></section>
    <section><h2 className="section-title fade-up">{t.timeline}</h2><div className="mt-4 space-y-3">{timeline.map((step, i) => <div key={step} className="timeline-step fade-up" style={{ animationDelay: `${i * 70}ms` }}><span className="timeline-dot">{i + 1}</span><span>{step}</span></div>)}</div></section>
    <section><h2 className="section-title fade-up">{t.faq}</h2><div className="mt-4 space-y-3">{faqs.map((q, i) => <div key={q} className="fade-up rounded-xl border bg-white p-4" style={{ animationDelay: `${i * 60}ms` }}>{q}</div>)}</div></section>
    <section className="fade-up rounded-3xl bg-red-700 p-8 text-center text-white"><h2 className="text-3xl font-bold">{t.finalTitle}</h2><div className="mt-5 flex flex-wrap justify-center gap-3"><Link href="/contact" className="btn-premium-red rounded-full px-5 py-2.5 font-semibold text-white">{t.consult}</Link><a href="https://wa.me/8801627442366" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/60 px-5 py-2.5 font-semibold transition duration-300 hover:-translate-y-1 hover:bg-white/10">{t.whatsapp}</a></div></section>
  </div></main>;
}
