"use client";
import Link from "next/link";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, ClipboardCheck, FileCheck2, GraduationCap, Handshake, Languages, Leaf, ShieldCheck, Users, Wrench } from "lucide-react";
import { useLanguage } from "@/components/layout/LanguageProvider";
import { translate } from "@/lib/i18n";
import { siteConfig } from "@/lib/site";

export default function HomePage() {
  const { language } = useLanguage();
  const t = translate({ bn: { headline: "জাপানে পড়াশোনা, কাজ ও ভবিষ্যৎ গড়ার সঠিক পথ", subtitle: "স্টুডেন্ট ভিসা, জব ভিসা, SSW/TITP, জাপানি ভাষা, স্কিল ট্রেইনিং, ডকুমেন্টেশন ও ইন্টারভিউ প্রস্তুতি—সবকিছুর জন্য এক জায়গায় KNLTC।", c1: "ফ্রি কনসাল্টেশন নিন", c2: "হোয়াটসঅ্যাপে কথা বলুন", details: "বিস্তারিত জানুন", apply: "এই সুযোগে আবেদন করুন", path: "আপনার জাপান পথ বেছে নিন", supportTitle: "জাপানে যাওয়ার জন্য যা যা প্রয়োজন — সবকিছু এক জায়গায়", supportSub: "ভাষা শিক্ষা থেকে শুরু করে ভিসা, স্কিল, ইন্টারভিউ, ডকুমেন্টেশন ও জাপানে পৌঁছানোর পরও প্রয়োজনীয় গাইডলাইন দিয়ে থাকে KNLTC।", opp: "বর্তমানে চলমান সুযোগসমূহ", process: "জাপানে যাওয়ার প্রক্রিয়া", whyJ: "কেন জাপান?", whyK: "কেন KNLTC?", trust: "বিশ্বাসের সাথে জাপান যাত্রা", finalT: "আপনার জাপান যাত্রা শুরু করতে প্রস্তুত?", finalS: "আপনার লক্ষ্য অনুযায়ী সঠিক পথ বুঝতে এখনই KNLTC-এর সাথে যোগাযোগ করুন।" }, en: { headline: "The right path to study, work, and build your future in Japan", subtitle: "Student visa, job visa, SSW/TITP, Japanese language, skill training, documentation, and interview preparation with KNLTC.", c1: "Get Free Consultation", c2: "Talk on WhatsApp", details: "Learn more", apply: "Apply for this opportunity", path: "Choose Your Japan Path", supportTitle: "Everything you need for Japan — in one place", supportSub: "Language training, visa support, skills, interviews, documentation, and after-arrival support.", opp: "Current Japan Opportunities", process: "Japan Journey Process", whyJ: "Why Japan?", whyK: "Why KNLTC?", trust: "Start your Japan journey with trust", finalT: "Ready to start your Japan journey?", finalS: "Contact KNLTC now to choose the right path for your goal." }, ja: { headline: "日本で学び、働き、未来を築くための正しい道", subtitle: "学生ビザ、就労ビザ、SSW/TITP、日本語、技能訓練、書類準備、面接対策をKNLTCが総合サポート。", c1: "無料相談を受ける", c2: "WhatsAppで相談", details: "詳しく見る", apply: "この機会に応募", path: "あなたの日本進路を選ぶ", supportTitle: "日本渡航に必要なすべてを一か所で", supportSub: "語学教育からビザ、技能、面接、書類、渡航後サポートまで。", opp: "現在募集中の機会", process: "日本渡航までの流れ", whyJ: "なぜ日本？", whyK: "なぜKNLTC？", trust: "信頼とともに日本へ", finalT: "日本への一歩を始める準備はできましたか？", finalS: "目標に合う進路を今すぐKNLTCと確認しましょう。" } }, language);

  const pathCards = translate({ bn: [{ icon: GraduationCap, title: "জাপানে পড়াশোনা", text: "ভাষা স্কুল, বিশ্ববিদ্যালয় ভর্তি, স্টুডেন্ট ভিসা, ডকুমেন্টেশন ও প্রি-ডিপার্চার গাইডলাইন।", cta: "স্টুডেন্ট ভিসা সম্পর্কে জানুন", href: "/study-in-japan" }, { icon: BriefcaseBusiness, title: "জাপানে কাজ", text: "SSW, TITP, স্কিল ট্রেইনিং, ইন্টারভিউ প্রস্তুতি, ডকুমেন্টেশন ও জব ভিসা গাইডলাইন।", cta: "জব ভিসা সম্পর্কে জানুন", href: "/work-in-japan" }, { icon: Languages, title: "জাপানি ভাষা", text: "N5/N4 প্রস্তুতি, JLPT/JFT গাইডলাইন, স্পোকেন জাপানিজ ও শেখার বই।", cta: "ভাষা শেখা শুরু করুন", href: "/japanese-language" }], en: [{ icon: GraduationCap, title: "Study in Japan", text: "Language school, university admission, student visa, documentation, and pre-departure guidance.", cta: "Learn about Student Visa", href: "/study-in-japan" }, { icon: BriefcaseBusiness, title: "Work in Japan", text: "SSW, TITP, skill training, interview prep, documentation, and job visa guidance.", cta: "Learn about Job Visa", href: "/work-in-japan" }, { icon: Languages, title: "Japanese Language", text: "N5/N4 prep, JLPT/JFT guidance, spoken Japanese, and learning resources.", cta: "Start learning", href: "/japanese-language" }], ja: [{ icon: GraduationCap, title: "日本留学", text: "日本語学校・大学進学・学生ビザ・書類準備・渡航前ガイド。", cta: "学生ビザを見る", href: "/study-in-japan" }, { icon: BriefcaseBusiness, title: "日本で働く", text: "SSW、TITP、技能訓練、面接対策、書類準備、就労ビザ。", cta: "就労ビザを見る", href: "/work-in-japan" }, { icon: Languages, title: "日本語", text: "N5/N4対策、JLPT/JFTガイド、会話練習、教材サポート。", cta: "学習を始める", href: "/japanese-language" }] }, language);

  const badges = translate({ bn: ["স্টুডেন্ট ভিসা সাপোর্ট", "জব ভিসা সাপোর্ট", "জাপানি ভাষা", "SSW/TITP"], en: ["Student Visa Support", "Job Visa Support", "Japanese Language", "SSW/TITP"], ja: ["学生ビザサポート", "就労ビザサポート", "日本語学習", "SSW/TITP"] }, language);
  const support = [[Languages, "ল্যাঙ্গুয়েজ প্রোগ্রাম", "অল্প সময়ে N5/N4 প্রস্তুতি ও জাপানি ভাষার শক্ত ভিত্তি তৈরিতে সহায়তা।"], [Wrench, "স্কিল ট্রেইনিং", "জাপানে যেসব স্কিলে কর্মী নেওয়া হয়, সেসব স্কিল ও স্কিল টেস্ট প্রস্তুতিতে সহায়তা।"], [GraduationCap, "স্টুডেন্ট ভিসা", "ভাষা স্কুল, বিশ্ববিদ্যালয় ভর্তি, ডকুমেন্টেশন ও স্টুডেন্ট ভিসা প্রসেসে গাইডলাইন।"], [BriefcaseBusiness, "জব ভিসা", "SSW ও TITP ভিসার জন্য যোগ্যতা, প্রস্তুতি ও প্রসেসিং সাপোর্ট।"], [Users, "ইন্টারভিউ প্রিপারেশন", "জাপানি প্রতিষ্ঠান বা কোম্পানির ইন্টারভিউয়ের জন্য মক ইন্টারভিউ ও প্রস্তুতি।"], [FileCheck2, "ডকুমেন্টেশন সাপোর্ট", "CV/Resume, ব্যাংক স্টেটমেন্ট, সার্টিফিকেট ও প্রয়োজনীয় ফাইল প্রস্তুতিতে সহায়তা।"], [Handshake, "আফটার অ্যারাইভাল সাপোর্ট", "জাপানে পৌঁছানোর পরও প্রয়োজনীয় খোঁজখবর ও গাইডলাইন দেওয়ার চেষ্টা।"]] as const;
  const opportunities = [["SSW Agriculture", "JLPT N4 অথবা JFT-Basic + Skill Test Certificate", "১৫০,০০০ – ২০০,০০০ ইয়েন"], ["SSW Caregiver", "JLPT N4 অথবা JFT-Basic + Skill Test Certificate", "১৮০,০০০ – ২২০,০০০ ইয়েন"], ["TITP Construction", "N5 লেভেলের জাপানি ভাষা থাকলে ভালো। প্রয়োজন হলে ভাষা শেখানো যায়।", "১৫০,০০০ – ২০০,০০০ ইয়েন"], ["TITP Automobile", "সংশ্লিষ্ট কাজের অভিজ্ঞতা থাকলে আবেদন করা যায়। প্রয়োজনীয় ভাষা শেখানো যায়।", "২০০,০০০ – ২৫০,০০০ ইয়েন"], ["TITP Welding", "সংশ্লিষ্ট কাজের অভিজ্ঞতা থাকলে আবেদন করা যায়। প্রয়োজনীয় ভাষা শেখানো যায়।", "২০০,০০০ – ২৫০,০০০ ইয়েন"]] as const;

  return <main className="bg-[#fcfaf7]">
    <section className="section-padding"><div className="container-narrow rounded-[2rem] border border-red-100 bg-white p-8 shadow-2xl"><h1 className="text-4xl font-black text-red-700">{t.headline}</h1><p className="mt-3 text-zinc-700">{t.subtitle}</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/contact" className="rounded-full bg-green-700 px-6 py-3 font-semibold text-white hover:-translate-y-1 transition">{t.c1}</Link><a href={siteConfig.whatsappHref} className="rounded-full border border-red-200 px-6 py-3 font-semibold text-red-700 hover:-translate-y-1 transition">{t.c2}</a></div><div className="mt-5 flex flex-wrap gap-2">{badges.map((b) => <span key={b} className="fade-up inline-flex items-center rounded-full bg-green-50 px-3 py-1 text-xs font-semibold text-green-700"><ShieldCheck className="mr-1 h-3 w-3" />{b}</span>)}</div></div></section>
    <section className="section-padding pt-0"><div className="container-narrow"><h2 className="section-title">{t.path}</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{pathCards.map((p) => { const Icon = p.icon; return <Link key={p.title} href={p.href} className="card-lift fade-up rounded-2xl border border-red-100 bg-white p-6 shadow-md"><Icon className="h-6 w-6 text-red-600" /><h3 className="mt-3 text-2xl font-bold text-red-700">{p.title}</h3><p className="mt-2 text-sm text-zinc-700">{p.text}</p><p className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-green-700">{p.cta}<ArrowRight className="h-4 w-4" /></p></Link>; })}</div></div></section>
    <section className="section-padding pt-0"><div className="container-narrow"><h2 className="section-title">{t.supportTitle}</h2><p className="section-subtitle">{t.supportSub}</p><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{support.map(([I,tt,tx],i)=><article key={tt} style={{animationDelay:`${i*60}ms`}} className="fade-up card-lift rounded-2xl border bg-white p-5 shadow-sm"><I className="h-6 w-6 text-green-700"/><h3 className="mt-3 font-bold text-red-700">{tt}</h3><p className="mt-2 text-sm text-zinc-700">{tx}</p></article>)}</div></div></section>
    <section className="section-padding pt-0"><div className="container-narrow"><h2 className="section-title">{t.opp}</h2><div className="mt-8 grid gap-4 lg:grid-cols-2">{opportunities.map(([name,elig,sal])=><article key={name} className="card-lift rounded-2xl border bg-white p-5 shadow-sm"><div className="flex gap-2 flex-wrap"><span className="rounded-full bg-red-100 px-3 py-1 text-xs font-semibold text-red-700">ভিসা সুযোগ</span><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-700">বেতন: {sal}</span></div><h3 className="mt-3 text-xl font-bold text-zinc-900">{name}</h3><p className="mt-2 text-sm text-zinc-700"><strong>যোগ্যতা:</strong> {elig}</p><button className="mt-4 rounded-full bg-green-700 px-4 py-2 text-sm font-semibold text-white hover:bg-green-800 transition">{t.apply}</button></article>)}</div></div></section>
    <section className="section-padding pt-0"><div className="container-narrow"><h2 className="section-title">{t.process}</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{["ফ্রি কনসাল্টেশন","ভাষা শিক্ষা","স্কিল ট্রেইনিং / অ্যাডমিশন প্রস্তুতি","ইন্টারভিউ প্রিপারেশন","ডকুমেন্টেশন","ভিসা প্রসেস","জাপান যাত্রা","আফটার অ্যারাইভাল সাপোর্ট"].map((s,i)=><div key={s} className="fade-up rounded-2xl border-l-4 border-green-600 bg-white p-4 shadow-sm"><p className="text-xs font-semibold text-red-700">ধাপ {i+1}</p><p className="font-semibold">{s}</p></div>)}</div></div></section>
    <section className="section-padding pt-0"><div className="container-narrow grid gap-6 lg:grid-cols-2"><div><h2 className="section-title">{t.whyJ}</h2><div className="mt-4 grid grid-cols-2 gap-3">{["নিরাপদ পরিবেশ","উন্নত প্রযুক্তি","ভবিষ্যৎ ক্যারিয়ার সুযোগ","আন্তর্জাতিক মানের শিক্ষা","শৃঙ্খলাপূর্ণ জীবন","দীর্ঘমেয়াদি সম্ভাবনা"].map((i)=><div key={i} className="rounded-xl border bg-white p-4 text-sm font-semibold"><Leaf className="mb-2 h-4 w-4 text-green-700"/>{i}</div>)}</div></div><div><h2 className="section-title">{t.whyK}</h2><div className="mt-4 grid grid-cols-2 gap-3">{["জাপান-কেন্দ্রিক গাইডলাইন","স্টুডেন্ট ও জব ভিসা সাপোর্ট","ভাষা + স্কিল সাপোর্ট","ডকুমেন্টেশন সাপোর্ট","ইন্টারভিউ প্রস্তুতি","জাপানে পৌঁছানোর পরও সম্পর্ক"].map((i)=><div key={i} className="rounded-xl border bg-white p-4 text-sm font-semibold"><BadgeCheck className="mb-2 h-4 w-4 text-red-700"/>{i}</div>)}</div></div></div></section>
    <section className="section-padding pt-0"><div className="container-narrow"><h2 className="section-title">{t.trust}</h2><div className="mt-6 grid gap-4 md:grid-cols-4">{[["৫০০+","গাইডলাইন"],["N5/N4","প্রস্তুতি"],["স্টুডেন্ট ও জব ভিসা","সাপোর্ট"],["SSW/TITP","পথ"]].map(([n,l])=><div key={n} className="fade-up rounded-2xl border bg-white p-5 text-center shadow-sm"><p className="text-2xl font-black text-red-700">{n}</p><p className="text-sm font-semibold text-zinc-700">{l}</p></div>)}</div></div></section>
    <section className="section-padding pt-0"><div className="container-narrow rounded-3xl bg-gradient-to-r from-red-700 to-green-700 p-8 text-center text-white"><h2 className="text-3xl font-black">{t.finalT}</h2><p className="mt-3">{t.finalS}</p><div className="mt-6 flex justify-center gap-3"><Link href="/contact" className="rounded-full bg-white px-6 py-3 font-semibold text-green-700">{t.c1}</Link><a href={siteConfig.whatsappHref} className="rounded-full border border-white px-6 py-3 font-semibold">{t.c2}</a></div></div></section>
  </main>;
}
