"use client";

import Link from "next/link";
import { useLanguage } from "@/components/layout/LanguageProvider";
import { translate } from "@/lib/i18n";

export default function WorkInJapanPage() {
  const { language } = useLanguage();
  const t = translate({ bn: { title: "জাপানে কাজের প্রস্তুতি ও ভিসা সাপোর্ট", subtitle: "SSW, TITP, স্কিল ট্রেইনিং, ইন্টারভিউ প্রস্তুতি, ডকুমেন্টেশন ও জাপানে পৌঁছানোর পর সাপোর্ট—সবকিছু এক জায়গায়।", compare: "SSW বনাম TITP", opportunities: "চলমান সুযোগসমূহ", sectors: "ওয়ার্ক সেক্টরসমূহ", timeline: "প্রসেস টাইমলাইন", finalTitle: "জাপানে কাজের প্রস্তুতি শুরু করতে চান?", apply: "আবেদন করুন", consult: "ফ্রি কনসাল্টেশন নিন" }, en: { title: "Work Preparation and Visa Support for Japan", subtitle: "SSW, TITP, skill training, interview preparation, documentation, and post-arrival support in one place.", compare: "SSW vs TITP", opportunities: "Current Opportunities", sectors: "Work Sectors", timeline: "Process Timeline", finalTitle: "Want to start preparing for work in Japan?", apply: "Apply", consult: "Get Free Consultation" }, ja: { title: "日本就職の準備とビザサポート", subtitle: "SSW、TITP、技能トレーニング、面接対策、書類準備、渡航後サポートまで一括対応。", compare: "SSWとTITPの比較", opportunities: "現在の募集機会", sectors: "就労分野", timeline: "プロセスタイムライン", finalTitle: "日本就職の準備を始めたいですか？", apply: "応募する", consult: "無料相談を受ける" } }, language);

  const compareCards = translate({ bn: [{ title: "SSW", items: ["JLPT N4 অথবা JFT-Basic", "স্কিল টেস্ট প্রয়োজন", "নির্দিষ্ট খাতে দক্ষ কর্মী হিসেবে কাজ", "ভবিষ্যতে Type 2 pathway"] }, { title: "TITP", items: ["ট্রেইনি ভিত্তিক প্রোগ্রাম", "N5 প্রস্তুতি থাকলে ভালো", "৩–৫ বছরের সুযোগ", "ভবিষ্যতে SSW pathway"] }], en: [{ title: "SSW", items: ["JLPT N4 or JFT-Basic", "Skill test required", "Work as skilled labor in specific sectors", "Type 2 pathway in future"] }, { title: "TITP", items: ["Trainee-based program", "N5 preparation is beneficial", "3–5 year opportunity", "Future pathway to SSW"] }], ja: [{ title: "SSW", items: ["JLPT N4またはJFT-Basic", "技能試験が必要", "特定分野で技能人材として就労", "将来的にType 2への道"] }, { title: "TITP", items: ["研修生ベースの制度", "N5準備があると有利", "3〜5年の機会", "将来SSWへの進路"] }] }, language);
  const opportunities = translate({ bn: [{ t: "SSW Agriculture", e: "ভাষা N4/JFT + বেসিক ফিজিক্যাল ফিটনেস", s: "বেতন: কোম্পানি নীতিমালা অনুযায়ী" }, { t: "SSW Caregiver", e: "ভাষা দক্ষতা + কেয়ারগিভিং প্রস্তুতি", s: "বেতন: সেক্টরভেদে নির্ধারিত" }, { t: "TITP Construction", e: "বেসিক ভাষা + ট্রেইনি মনোভাব", s: "বেতন: প্রতিষ্ঠানের শর্ত অনুযায়ী" }, { t: "TITP Automobile", e: "টেকনিক্যাল আগ্রহ + বেসিক ভাষা", s: "বেতন: দক্ষতা ও পদের ওপর নির্ভরশীল" }, { t: "TITP Welding", e: "হ্যান্ডস-অন স্কিল আগ্রহ + ভাষা প্রস্তুতি", s: "বেতন: সেক্টরভিত্তিক" }], en: [{ t: "SSW Agriculture", e: "N4/JFT + basic physical fitness", s: "Salary: As per company policy" }, { t: "SSW Caregiver", e: "Language skill + caregiver readiness", s: "Salary: Sector dependent" }, { t: "TITP Construction", e: "Basic language + trainee mindset", s: "Salary: As per institution terms" }, { t: "TITP Automobile", e: "Technical interest + basic language", s: "Salary: Depends on role and skill" }, { t: "TITP Welding", e: "Hands-on skill interest + language prep", s: "Salary: Sector-based" }], ja: [{ t: "SSW 農業", e: "N4/JFTと基本体力", s: "給与: 企業規定による" }, { t: "SSW 介護", e: "語学力と介護準備", s: "給与: 分野により異なる" }, { t: "TITP 建設", e: "基礎語学と研修姿勢", s: "給与: 受入先条件による" }, { t: "TITP 自動車", e: "技術への関心と基礎語学", s: "給与: 役割・技能による" }, { t: "TITP 溶接", e: "実技志向と語学準備", s: "給与: 分野別" }] }, language);
  const sectors = translate({ bn: ["নার্সিং কেয়ার", "কৃষি", "নির্মাণ", "ফুড সার্ভিস", "অটোমোবাইল রিপেয়ার", "ইন্ডাস্ট্রিয়াল সাপোর্ট"], en: ["Nursing Care", "Agriculture", "Construction", "Food Service", "Automobile Repair", "Industrial Support"], ja: ["介護", "農業", "建設", "外食業", "自動車整備", "産業サポート"] }, language);
  const timeline = translate({ bn: ["কনসাল্টেশন", "ভাষা প্রস্তুতি", "স্কিল ট্রেইনিং", "ইন্টারভিউ প্রস্তুতি", "ডকুমেন্টেশন", "ভিসা প্রসেস", "জাপানে পৌঁছানোর পর সাপোর্ট"], en: ["Consultation", "Language preparation", "Skill training", "Interview preparation", "Documentation", "Visa process", "After-arrival support in Japan"], ja: ["相談", "語学準備", "技能トレーニング", "面接準備", "書類準備", "ビザ手続き", "渡航後サポート"] }, language);

  return <main className="section-padding bg-gradient-to-b from-white via-red-50/20 to-green-50/30"><div className="container-narrow space-y-6">
    <section className="fade-up rounded-3xl border bg-white p-8 shadow-sm md:p-10"><h1 className="text-3xl font-extrabold text-red-700 md:text-4xl">{t.title}</h1><p className="mt-3 text-muted-foreground">{t.subtitle}</p></section>
    <section><h2 className="section-title fade-up">{t.compare}</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{compareCards.map((c, i) => <div key={c.title} className="fade-up card-lift rounded-2xl border bg-white p-5" style={{ animationDelay: `${i * 110}ms` }}><h3 className="text-xl font-bold text-red-700">{c.title}</h3><ul className="mt-3 space-y-2 text-sm">{c.items.map((x) => <li key={x}>• {x}</li>)}</ul></div>)}</div></section>
    <section><h2 className="section-title fade-up">{t.opportunities}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{opportunities.map((op, i) => <div key={op.t} className="fade-up card-lift rounded-xl border bg-white p-5" style={{ animationDelay: `${i * 70}ms` }}><h3 className="font-bold">{op.t}</h3><p className="mt-2 text-sm text-muted-foreground">{translate({bn:"যোগ্যতা:",en:"Eligibility:",ja:"応募条件:"},language)} {op.e}</p><p className="mt-1 text-sm text-muted-foreground">{op.s}</p><Link href="/contact" className="btn-premium-green mt-4 inline-block rounded-full border px-4 py-2 text-sm font-semibold">{t.apply}</Link></div>)}</div></section>
    <section><h2 className="section-title fade-up">{t.sectors}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sectors.map((x, i) => <div key={x} className="fade-up card-lift rounded-xl border border-red-100 bg-red-50/50 p-3 text-sm font-medium text-red-700" style={{ animationDelay: `${i * 60}ms` }}>{x}</div>)}</div></section>
    <section><h2 className="section-title fade-up">{t.timeline}</h2><div className="mt-4 space-y-3">{timeline.map((x, i) => <div key={x} className="timeline-step fade-up" style={{ animationDelay: `${i * 70}ms` }}><span className="timeline-dot">{i + 1}</span><span>{x}</span></div>)}</div></section>
    <section className="fade-up rounded-3xl bg-red-700 p-8 text-center text-white"><h2 className="text-3xl font-bold">{t.finalTitle}</h2><Link href="/contact" className="mt-5 inline-block rounded-full bg-white px-6 py-3 font-semibold text-red-700 transition duration-300 hover:-translate-y-1 hover:bg-green-100">{t.consult}</Link></section>
  </div></main>;
}
