import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, FileCheck2, Languages, MessageCircle, Plane, Sparkles, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { siteConfig } from "@/lib/site";
export const metadata: Metadata = { title: "Japan Career Pathway", description: "Structured Japan career guidance with SSW/TITP pathways, language preparation, interview training, documentation support, and after-arrival assistance." };
const sections = [{ title: "SSW Visa", desc: "Understand eligibility, sector requirements, language benchmarks, and practical preparation roadmap.", icon: BriefcaseBusiness },{ title: "TITP Program", desc: "Step-by-step trainee pathway guidance with transparent expectations and process clarity.", icon: Wrench },{ title: "Skill Training", desc: "Industry-oriented skills development aligned with Japan career opportunities.", icon: Sparkles },{ title: "Japanese Language Requirement", desc: "JLPT-focused preparation and workplace communication practice for career readiness.", icon: Languages },{ title: "Interview Preparation", desc: "Mock interviews, communication coaching, and employer-facing profile preparation.", icon: CheckCircle2 },{ title: "Documentation Support", desc: "Guided document planning, compliance checks, and submission readiness support.", icon: FileCheck2 },{ title: "After Arrival Support", desc: "Orientation support for adaptation, communication, and next-step settlement basics.", icon: Plane }];
export default function JapanCareerPage(){return <section className="section-padding bg-gradient-to-b from-slate-50 via-background to-rose-50/30"><div className="container-narrow space-y-8"><div className="rounded-2xl border bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-semibold text-accent">Japan Career Pathway</p><h1 className="mt-2 text-3xl font-bold tracking-tight md:text-4xl">Work & Career in Japan</h1><p className="mt-3 max-w-3xl text-muted-foreground">Premium end-to-end preparation for Japan-focused career pathways through language, skills, interview readiness, and documentation support.</p><div className="mt-5 flex flex-wrap gap-3"><Button asChild><Link href="/contact">Apply Now</Link></Button><Button asChild variant="outline"><a href={siteConfig.whatsappHref} target="_blank" rel="noopener noreferrer"><MessageCircle className="mr-2 h-4 w-4" />WhatsApp</a></Button></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sections.map((section) => {const Icon = section.icon; return <Card key={section.title} className="border-border/80 bg-white"><CardHeader><div className="inline-flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="h-5 w-5" /></div><CardTitle className="text-xl">{section.title}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{section.desc}</p></CardContent></Card>;})}</div><div className="rounded-2xl border bg-white p-6 text-center shadow-sm md:p-8"><h2 className="text-2xl font-bold">Ready to begin your Japan career preparation?</h2><p className="mx-auto mt-2 max-w-2xl text-sm text-muted-foreground">Start with a structured consultation and choose the most suitable pathway.</p><div className="mt-5 flex flex-wrap items-center justify-center gap-3"><Button asChild><Link href="/contact">Apply for Consultation <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild variant="outline"><a href={siteConfig.whatsappHref} target="_blank" rel="noopener noreferrer">Talk on WhatsApp</a></Button></div></div></div></section>;}
